import { GoogleGenAI, Type } from "@google/genai";
import { Category, Season, ClothingItem } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

interface AnalysisResult {
  category: string;
  subCategory: string;
  colors: string[];
  seasons: string[];
  tags: string[];
  styleDescription: string;
}

export const analyzeImage = async (base64Image: string): Promise<AnalysisResult> => {
  try {
    // Remove data URL prefix if present for the API call
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview', // Switch to a model that supports JSON mode and vision
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', // Assuming jpeg for simplicity, API handles others too
              data: cleanBase64,
            },
          },
          {
            text: `Analyze this fashion item. Identify the category (Tops, Bottoms, Outerwear, Shoes, Accessories, Dresses), 
            specific sub-category (e.g., Graphic Tee, Pleated Skirt), dominant colors, suitable seasons, and style tags (e.g., boho, minimal, streetwear).
            Also provide a short 1-sentence style description.`
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            category: { type: Type.STRING, enum: Object.values(Category) },
            subCategory: { type: Type.STRING },
            colors: { type: Type.ARRAY, items: { type: Type.STRING } },
            seasons: { type: Type.ARRAY, items: { type: Type.STRING } },
            tags: { type: Type.ARRAY, items: { type: Type.STRING } },
            styleDescription: { type: Type.STRING },
          },
        },
      },
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");
    
    return JSON.parse(text) as AnalysisResult;

  } catch (error) {
    console.error("Error analyzing image:", error);
    // Fallback data if AI fails
    return {
      category: Category.TOPS,
      subCategory: "Unknown",
      colors: ["Unknown"],
      seasons: [Season.ALL_SEASON],
      tags: [],
      styleDescription: "Could not analyze image."
    };
  }
};

export const removeBackground = async (base64Image: string): Promise<string> => {
  try {
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64,
            },
          },
          {
            text: 'Remove the background from this image. Return the object on a transparent background.',
          },
        ],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");

  } catch (error) {
    console.error("Error removing background:", error);
    throw error;
  }
};

export const suggestOutfit = async (items: ClothingItem[], weather: string = "sunny"): Promise<string> => {
  try {
    if (items.length === 0) {
      return "Your wardrobe is empty! Add some items so I can style you.";
    }

    const itemsDescription = items.map(i => 
      `- ${i.subCategory} (${i.color.join(', ')}), Category: ${i.category}, Seasons: ${i.season.join(', ')}, Tags: ${i.tags.join(', ')}`
    ).join('\n');

    const prompt = `
      You are a professional personal stylist. 
      The weather condition today is: ${weather}.
      
      Here is the list of items in the user's wardrobe:
      ${itemsDescription}

      Please suggest a stylish and cohesive outfit from these specific items that matches the weather. 
      Explain why you chose these pieces and how they work together. 
      If no perfect match exists, suggest the best possible combination and mention what might be missing (e.g., "Add a coat if you have one").
      Keep the response concise, encouraging, and fashion-forward.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
    });

    return response.text || "I couldn't generate a suggestion at this time.";

  } catch (error) {
    console.error("Error suggesting outfit:", error);
    return "I'm having trouble connecting to your personal stylist right now.";
  }
}